# # EVERFOREST
[colors.primary]
background = "#333c43"
foreground = "#d3c6aa"

[colors.normal]
black = "#4d5960"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"

[colors.bright]
black = "#4d5960"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"

[font]
# size = 12.5
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "IosevkaTerm Nerd Font Mono"
# family= "BlexMono Nerd Font Mono"
style = "Light"

[window]
decorations = "buttonless"
dynamic_title = true
startup_mode = "Windowed"
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 120
lines = 36

[cursor]
blink_interval = 250

[cursor.style]
shape = "Block"
blinking = "Always"

[window.padding]
x = 30
y = 30
